version: '3'
services:
  fhir-server:
    image: hapiproject/hapi:latest
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    volumes:
      - ./data_fhir:/var/lib/mysql

  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=fhirdb
    volumes:
      - ./data_db:/var/lib/mysql

    restart: unless-stopped
    networks:
      - red_fhir

networks:
  red_fhir:
    ipam:
      driver: default
      config:
        - subnet: 192.168.9.0/24