version: '3'
services:
  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - red_interna_porteiner

networks:
  red_interna_porteiner:
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24